### ISSUE TITLE
Could you tell me the structure of the dataset and where to download it?

### ISSUE THREAD

**Issue by pangda72** [LynnHg/Pytorch-medical-image-segmentation#1]
Hi @LynnHg 

Thanks for your code ,could you tell me the structure of the dataset and where to dowanload it?

Thanks in advance!
Best.

**Comment by LynnHg** [comment]
You can obtain the dataset from [http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/](http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/)

**Comment by pangda72** [comment]
> You can obtain the dataset from http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/

Thank you.you've been very grateful!
