### ISSUE TITLE
some quries

### ISSUE THREAD

**Issue by pangda72** [LynnHg/Pytorch-medical-image-segmentation#2]
Hi @LynnHg 

I'm using this repo to segment medical grayscale images on a private dataset.It is a binary classification.At the same time, I refer to your blog:Bladder wall segmentation and tumor detection based on MRI 

But my results look something like this:
![result](https://user-images.githubusercontent.com/74399643/138391457-185efd97-76f6-4b86-936d-2e5fef1d2a33.png)

I don't know why the original image is so blurry, And the segmentation effect is not very good, but the dice value is very high, I don't know what the problem is .could you give me some help?

Thanks in advance.
Best wishes.

**Comment by LynnHg** [comment]
You should check whether the blurred image is original data or processed data. Is there a problem with data preprocessing?

**Comment by pangda72** [comment]
> You should check whether the blurred image is original data or processed data. Is there a problem with data preprocessing?

 Hi @LynnHg 
Thanks for your prompt reply.This will help me a lot and I will try as you suggest.
